---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: laas-memelord
  labels:
    app: laas-grafana
spec:
  serviceName: laas-grafana
  replicas: 1
  selector:
    matchLabels:
      app: laas-grafana
  template:
    metadata:
      labels:
        app: laas-grafana
    spec:
      containers:
        - name: laas-grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_DATABASE_TYPE
              value: sqlite3
            - name: GF_DATABASE_PATH
              value: /var/lib/grafana/grafana.db
            - name: GF_AUTH_GENERIC_OAUTH_SIGNOUT_REDIRECT_URL
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oidc-client-laas-memelord-owner-secrets
                  key: OIDC_CLIENT_ID
            - name: GF_AUTH_GENERIC_OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: "oidc-client-laas-memelord-owner-secrets"
                  key: OIDC_CLIENT_SECRET
            - name: GF_AUTH_GENERIC_OAUTH_SCOPES
              value: openid,profile
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: "oidc-client-laas-memelord-owner-secrets"
                  key: OIDC_IDP_AUTH_URI
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              valueFrom:
                secretKeyRef:
                  name: "oidc-client-laas-memelord-owner-secrets"
                  key: OIDC_IDP_TOKEN_URI
            - name: GF_AUTH_GENERIC_OAUTH_API_URL
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: grafana-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: sqlite
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: laas-grafana
  labels:
    app: laas-grafana
spec:
  type: ClusterIP
  selector:
    app: laas-grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: laas-grafana
spec:
  secretName: laas-grafana-tls
  dnsNames:
    - laas-grafana.ee-lte-1.codemowers.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laas-grafana
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: laas-grafana.ee-lte-1.codemowers.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: laas-grafana
                port:
                  number: 80
  tls:
    - secretName: laas-grafana-tls
---
apiVersion: codemowers.cloud/v1beta1
kind: OIDCClient
metadata:
  name: laas-grafana
spec:
  displayName: Laas Grafana
  uri: https://laas-grafana.ee-lte-1.codemowers.io/oidc/authenticate/
  redirectUris:
    - https://laas-grafana.ee-lte-1.codemowers.io/oidc/callback/
  grantTypes:
    - authorization_code
    - refresh_token
  responseTypes:
    - code
  availableScopes:
    - openid
    - profile
  pkce: false
