---
apiVersion: codemowers.cloud/v1beta1
kind: OIDCClient
metadata:
  name: "laas-memelord"
spec:
  displayName: "Laas Memelord"
  uri: "https://{{ .Values.hostname }}.{{ .Values.domain }}/"
  redirectUris:
    - "https://{{ .Values.hostname }}.{{ .Values.domain }}/oidc/callback/"
  grantTypes:
    - authorization_code
    - refresh_token
  responseTypes:
    - code
  availableScopes:
    - openid
    - profile
  pkce: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laas-memelord-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laas-memelord-app
  template:
    metadata:
      labels:
        app: laas-memelord-app
    spec:
      containers:
        - name: memelord
          image: ghcr.io/l4rm4nd/memelord:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: TZ
              value: Europe/Tallinn
            - name: DB_ENGINE
              value: postgres
            - name: POSTGRES_HOST
              value: laas-memelord-database-rw
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: laas-memelord-database-app
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: laas-memelord-database
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laas-memelord-database
                  key: password
            - name: POSTGRES_DB
              value: postgres 
            - name: DOMAIN
              value: "laas-memelord.ee-lte-1.codemowers.io,localhost"
            - name: REDIS_HOST
              value: laas-memelord-redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laas-memelord-redis
                  key: redis-password
            - name: OIDC_ENABLED
              value: "True"
            - name: OIDC_AUTOLOGIN
              value: "False"
            - name: OIDC_CREATE_USER
              value: "True"
            - name: OIDC_OP_JWKS_ENDPOINT
              value: https://auth.ee-lte-1.codemowers.io/jwks
            - name: OIDC_RP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oidc-client-laas-memelord-owner-secrets
                  key: OIDC_CLIENT_ID
            - name: OIDC_RP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "oidc-client-laas-memelord-owner-secrets"
                  key: OIDC_CLIENT_SECRET
            - name: OIDC_RP_AUTHORIZATION_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: "oidc-client-laas-memelord-owner-secrets"
                  key: OIDC_IDP_AUTH_URI
            - name: OIDC_OP_TOKEN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: "oidc-client-laas-memelord-owner-secrets"
                  key: OIDC_IDP_TOKEN_URI
            - name: OIDC_OP_USER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: "oidc-client-laas-memelord-owner-secrets"
                  key: OIDC_IDP_USERINFO_URI
            - name: OIDC_RP_SIGN_ALGO
              valueFrom:
                secretKeyRef:
                  name: "oidc-client-laas-memelord-owner-secrets"
                  key: OIDC_ID_TOKEN_SIGNED_RESPONSE_ALG
                  
---
apiVersion: v1
kind: Service
metadata:
  name: laas-memelord
spec:
  type: ClusterIP
  selector:
    app: laas-memelord-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: laas-memelord
spec:
  secretName: laas-memelord-tls
  dnsNames:
    - laas-memelord.ee-lte-1.codemowers.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laas-memelord
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: laas-memelord.ee-lte-1.codemowers.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: laas-memelord
                port:
                  number: 80
  tls:
    - secretName: laas-memelord-tls
